apiVersion: v1
kind: Namespace
metadata:
  name: development
  labels:
    name: development-test
    
---
apiVersion: v1
kind: Secret
metadata:
  name: myregistrykeyy
  namespace: development
data:
  .dockerconfigjson: ewoJImF1dGhzIjogewoJCSJodHRwczovL2luZGV4LmRvY2tlci5pby92MS8iOiB7CgkJCSJhdXRoIjogImFtbHphRzUxYW05emFIazZjMmhoYVhKemIyNHkiCgkJfQoJfQp9
type: kubernetes.io/dockerconfigjson    
    
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pythonapp-deployment
  namespace: development
  labels:
    app: pythonapp
spec:
  replicas: 3
  selector:
    matchLabels:
      app: pythonapp
  template:
    metadata:
      labels:
        app: pythonapp 
    spec:
      containers:
      - name: pythonappserver
        image: jishnujoshy/pythonapp:latest
        ports:
        - containerPort: 5000
      imagePullSecrets:
      - name: regcred
        
        
---

apiVersion: v1
kind: Service
metadata:
  name: pythonapp-service
  namespace: development
spec:
  selector:
    app: pythonapp 
  type: NodePort
  ports:
  - protocol: TCP
    port: 5000
    targetPort: 5000
